apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  WORDPRESS_DB_NAME: my-wordpress
  WORDPRESS_DB_USER: my-wordpress
  WORDPRESS_DB_HOST: mysql-service
  MYSQL_DATABASE: my-wordpress
  MYSQL_USER: my-wordpress

