apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: password
  WORDPRESS_DB_HOST: mysql-service
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
